version: "2"
services:
  api:
    build:
      context: api 
      dockerfile: Dockerfile
    ports:
      - "80:80" # web
  db:
    expose:
       - 3306
    environment:
       - MYSQL_ROOT_PASSWORD=bob
       - MYSQL_DATABASE=todo
    build:
      context: db 
      dockerfile: Dockerfile
